TRUNCATE TABLE GOLD.FACT_SECURITY_DAILY_METRICS;
TRUNCATE TABLE GOLD.FACT_DAILY_PRICE;
TRUNCATE TABLE GOLD.DIM_SECURITY;
TRUNCATE TABLE GOLD.DIM_SECTOR;
TRUNCATE TABLE GOLD.DIM_DATE;

INSERT INTO GOLD.DIM_DATE (
    DATE_KEY,
    TRADING_DATE,
    DAY_OF_WEEK_NAME,
    DAY_OF_MONTH,
    WEEK_OF_YEAR,
    MONTH_NUMBER,
    MONTH_NAME,
    QUARTER_NUMBER,
    YEAR_NUMBER,
    IS_WEEKDAY,
    IS_TRADING_DAY
)
SELECT
    TO_NUMBER(TO_CHAR(TRADING_DATE, 'YYYYMMDD')) AS DATE_KEY,
    TRADING_DATE,
    DAYNAME(TRADING_DATE) AS DAY_OF_WEEK_NAME,
    DAY(TRADING_DATE) AS DAY_OF_MONTH,
    WEEKOFYEAR(TRADING_DATE) AS WEEK_OF_YEAR,
    MONTH(TRADING_DATE) AS MONTH_NUMBER,
    MONTHNAME(TRADING_DATE) AS MONTH_NAME,
    QUARTER(TRADING_DATE) AS QUARTER_NUMBER,
    YEAR(TRADING_DATE) AS YEAR_NUMBER,
    IS_WEEKDAY,
    TRUE AS IS_TRADING_DAY
FROM SILVER.STG_TRADING_CALENDAR;

INSERT INTO GOLD.DIM_SECTOR (
    SECTOR_KEY,
    SECTOR,
    INDUSTRY,
    SECTOR_INDUSTRY_NAME
)
SELECT DISTINCT
    ABS(HASH(SECTOR, INDUSTRY)) AS SECTOR_KEY,
    SECTOR,
    INDUSTRY,
    SECTOR || ' / ' || INDUSTRY AS SECTOR_INDUSTRY_NAME
FROM SILVER.STG_SECURITY;

INSERT INTO GOLD.DIM_SECURITY (
    SECURITY_KEY,
    SECTOR_KEY,
    SYMBOL,
    COMPANY_NAME,
    SECTOR,
    INDUSTRY,
    IS_ACTIVE,
    EFFECTIVE_START_DATE,
    EFFECTIVE_END_DATE,
    IS_CURRENT
)
SELECT
    ABS(HASH(s.SYMBOL)) AS SECURITY_KEY,
    ds.SECTOR_KEY,
    s.SYMBOL,
    s.COMPANY_NAME,
    s.SECTOR,
    s.INDUSTRY,
    s.IS_ACTIVE,
    TO_DATE('1900-01-01') AS EFFECTIVE_START_DATE,
    NULL AS EFFECTIVE_END_DATE,
    TRUE AS IS_CURRENT
FROM SILVER.STG_SECURITY s
JOIN GOLD.DIM_SECTOR ds
    ON s.SECTOR = ds.SECTOR
    AND s.INDUSTRY = ds.INDUSTRY;

INSERT INTO GOLD.FACT_DAILY_PRICE (
    DATE_KEY,
    SECURITY_KEY,
    OPEN_PRICE,
    HIGH_PRICE,
    LOW_PRICE,
    CLOSE_PRICE,
    VOLUME,
    DOLLAR_VOLUME,
    INTRADAY_RANGE
)
SELECT
    dd.DATE_KEY,
    ds.SECURITY_KEY,
    p.OPEN_PRICE,
    p.HIGH_PRICE,
    p.LOW_PRICE,
    p.CLOSE_PRICE,
    p.VOLUME,
    p.CLOSE_PRICE * p.VOLUME AS DOLLAR_VOLUME,
    p.HIGH_PRICE - p.LOW_PRICE AS INTRADAY_RANGE
FROM SILVER.STG_DAILY_PRICE p
JOIN GOLD.DIM_DATE dd
    ON p.TRADING_DATE = dd.TRADING_DATE
JOIN GOLD.DIM_SECURITY ds
    ON p.SYMBOL = ds.SYMBOL
WHERE ds.IS_CURRENT = TRUE;

INSERT INTO GOLD.FACT_SECURITY_DAILY_METRICS (
    DATE_KEY,
    SECURITY_KEY,
    PRIOR_CLOSE_PRICE,
    DAILY_RETURN,
    ROLLING_7_DAY_RETURN,
    ROLLING_30_DAY_RETURN,
    ROLLING_7_DAY_VOLATILITY,
    MA_7_CLOSE_PRICE,
    MA_30_CLOSE_PRICE,
    AVG_30_DAY_VOLUME,
    VOLUME_SPIKE_FLAG,
    MOVING_AVERAGE_SIGNAL,
    TOP_GAINER_RANK,
    TOP_LOSER_RANK,
    DAILY_RETURN_RANK,
    PRIOR_DAILY_RETURN_RANK,
    RANK_MOVEMENT
)
WITH base_prices AS (
    SELECT
        f.DATE_KEY,
        dd.TRADING_DATE,
        f.SECURITY_KEY,
        f.CLOSE_PRICE,
        f.VOLUME,
        LAG(f.CLOSE_PRICE, 1) OVER (
            PARTITION BY f.SECURITY_KEY
            ORDER BY dd.TRADING_DATE
        ) AS PRIOR_CLOSE_PRICE,
        LAG(f.CLOSE_PRICE, 7) OVER (
            PARTITION BY f.SECURITY_KEY
            ORDER BY dd.TRADING_DATE
        ) AS CLOSE_PRICE_7_DAYS_AGO,
        LAG(f.CLOSE_PRICE, 30) OVER (
            PARTITION BY f.SECURITY_KEY
            ORDER BY dd.TRADING_DATE
        ) AS CLOSE_PRICE_30_DAYS_AGO,
        AVG(f.CLOSE_PRICE) OVER (
            PARTITION BY f.SECURITY_KEY
            ORDER BY dd.TRADING_DATE
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ) AS MA_7_CLOSE_PRICE,
        AVG(f.CLOSE_PRICE) OVER (
            PARTITION BY f.SECURITY_KEY
            ORDER BY dd.TRADING_DATE
            ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
        ) AS MA_30_CLOSE_PRICE,
        AVG(f.VOLUME) OVER (
            PARTITION BY f.SECURITY_KEY
            ORDER BY dd.TRADING_DATE
            ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
        ) AS AVG_30_DAY_VOLUME
    FROM GOLD.FACT_DAILY_PRICE f
    JOIN GOLD.DIM_DATE dd
        ON f.DATE_KEY = dd.DATE_KEY
),
return_metrics AS (
    SELECT
        *,
        CASE
            WHEN PRIOR_CLOSE_PRICE IS NULL OR PRIOR_CLOSE_PRICE = 0 THEN NULL
            ELSE (CLOSE_PRICE - PRIOR_CLOSE_PRICE) / PRIOR_CLOSE_PRICE
        END AS DAILY_RETURN,
        CASE
            WHEN CLOSE_PRICE_7_DAYS_AGO IS NULL OR CLOSE_PRICE_7_DAYS_AGO = 0 THEN NULL
            ELSE (CLOSE_PRICE - CLOSE_PRICE_7_DAYS_AGO) / CLOSE_PRICE_7_DAYS_AGO
        END AS ROLLING_7_DAY_RETURN,
        CASE
            WHEN CLOSE_PRICE_30_DAYS_AGO IS NULL OR CLOSE_PRICE_30_DAYS_AGO = 0 THEN NULL
            ELSE (CLOSE_PRICE - CLOSE_PRICE_30_DAYS_AGO) / CLOSE_PRICE_30_DAYS_AGO
        END AS ROLLING_30_DAY_RETURN
    FROM base_prices
),
ranked_metrics AS (
    SELECT
        *,
        STDDEV_SAMP(DAILY_RETURN) OVER (
            PARTITION BY SECURITY_KEY
            ORDER BY TRADING_DATE
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ) AS ROLLING_7_DAY_VOLATILITY,
        CASE
            WHEN AVG_30_DAY_VOLUME IS NULL THEN FALSE
            ELSE VOLUME > (AVG_30_DAY_VOLUME * 2)
        END AS VOLUME_SPIKE_FLAG,
        CASE
            WHEN MA_7_CLOSE_PRICE IS NULL OR MA_30_CLOSE_PRICE IS NULL THEN 'insufficient_history'
            WHEN MA_7_CLOSE_PRICE > MA_30_CLOSE_PRICE THEN 'bullish'
            ELSE 'bearish'
        END AS MOVING_AVERAGE_SIGNAL,
        DENSE_RANK() OVER (
            PARTITION BY DATE_KEY
            ORDER BY DAILY_RETURN DESC NULLS LAST
        ) AS TOP_GAINER_RANK,
        DENSE_RANK() OVER (
            PARTITION BY DATE_KEY
            ORDER BY DAILY_RETURN ASC NULLS LAST
        ) AS TOP_LOSER_RANK,
        DENSE_RANK() OVER (
            PARTITION BY DATE_KEY
            ORDER BY DAILY_RETURN DESC NULLS LAST
        ) AS DAILY_RETURN_RANK
    FROM return_metrics
),
rank_movement AS (
    SELECT
        *,
        LAG(DAILY_RETURN_RANK) OVER (
            PARTITION BY SECURITY_KEY
            ORDER BY TRADING_DATE
        ) AS PRIOR_DAILY_RETURN_RANK
    FROM ranked_metrics
)
SELECT
    DATE_KEY,
    SECURITY_KEY,
    PRIOR_CLOSE_PRICE,
    DAILY_RETURN,
    ROLLING_7_DAY_RETURN,
    ROLLING_30_DAY_RETURN,
    ROLLING_7_DAY_VOLATILITY,
    MA_7_CLOSE_PRICE,
    MA_30_CLOSE_PRICE,
    AVG_30_DAY_VOLUME,
    VOLUME_SPIKE_FLAG,
    MOVING_AVERAGE_SIGNAL,
    TOP_GAINER_RANK,
    TOP_LOSER_RANK,
    DAILY_RETURN_RANK,
    PRIOR_DAILY_RETURN_RANK,
    PRIOR_DAILY_RETURN_RANK - DAILY_RETURN_RANK AS RANK_MOVEMENT
FROM rank_movement;

CREATE OR REPLACE TABLE GOLD.MART_NASDAQ_MARKET_MOMENTUM AS
WITH top_gainers AS (
    SELECT
        m.DATE_KEY,
        s.SYMBOL,
        m.DAILY_RETURN
    FROM GOLD.FACT_SECURITY_DAILY_METRICS m
    JOIN GOLD.DIM_SECURITY s
        ON m.SECURITY_KEY = s.SECURITY_KEY
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY m.DATE_KEY
        ORDER BY m.DAILY_RETURN DESC NULLS LAST, s.SYMBOL
    ) = 1
),
top_losers AS (
    SELECT
        m.DATE_KEY,
        s.SYMBOL,
        m.DAILY_RETURN
    FROM GOLD.FACT_SECURITY_DAILY_METRICS m
    JOIN GOLD.DIM_SECURITY s
        ON m.SECURITY_KEY = s.SECURITY_KEY
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY m.DATE_KEY
        ORDER BY m.DAILY_RETURN ASC NULLS LAST, s.SYMBOL
    ) = 1
)
SELECT
    dd.DATE_KEY,
    dd.TRADING_DATE,
    COUNT(*) AS SECURITY_COUNT,
    COUNT_IF(m.DAILY_RETURN > 0) AS ADVANCING_SECURITY_COUNT,
    COUNT_IF(m.DAILY_RETURN < 0) AS DECLINING_SECURITY_COUNT,
    COUNT_IF(m.DAILY_RETURN = 0 OR m.DAILY_RETURN IS NULL) AS FLAT_SECURITY_COUNT,
    AVG(m.DAILY_RETURN) AS AVERAGE_DAILY_RETURN,
    SUM(f.VOLUME) AS TOTAL_VOLUME,
    COUNT_IF(m.VOLUME_SPIKE_FLAG) AS VOLUME_SPIKE_COUNT,
    g.SYMBOL AS TOP_GAINER_SYMBOL,
    g.DAILY_RETURN AS TOP_GAINER_RETURN,
    l.SYMBOL AS TOP_LOSER_SYMBOL,
    l.DAILY_RETURN AS TOP_LOSER_RETURN,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM GOLD.FACT_SECURITY_DAILY_METRICS m
JOIN GOLD.FACT_DAILY_PRICE f
    ON m.DATE_KEY = f.DATE_KEY
    AND m.SECURITY_KEY = f.SECURITY_KEY
JOIN GOLD.DIM_DATE dd
    ON m.DATE_KEY = dd.DATE_KEY
LEFT JOIN top_gainers g
    ON m.DATE_KEY = g.DATE_KEY
LEFT JOIN top_losers l
    ON m.DATE_KEY = l.DATE_KEY
GROUP BY
    dd.DATE_KEY,
    dd.TRADING_DATE,
    g.SYMBOL,
    g.DAILY_RETURN,
    l.SYMBOL,
    l.DAILY_RETURN;

CREATE OR REPLACE TABLE GOLD.MART_SECTOR_PERFORMANCE AS
SELECT
    dd.DATE_KEY,
    dd.TRADING_DATE,
    sec.SECTOR_KEY,
    sec.SECTOR,
    COUNT(*) AS SECURITY_COUNT,
    AVG(m.DAILY_RETURN) AS AVERAGE_DAILY_RETURN,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY m.DAILY_RETURN) AS MEDIAN_DAILY_RETURN,
    SUM(f.VOLUME) AS TOTAL_VOLUME,
    AVG(m.ROLLING_7_DAY_VOLATILITY) AS AVERAGE_ROLLING_7_DAY_VOLATILITY,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM GOLD.FACT_SECURITY_DAILY_METRICS m
JOIN GOLD.FACT_DAILY_PRICE f
    ON m.DATE_KEY = f.DATE_KEY
    AND m.SECURITY_KEY = f.SECURITY_KEY
JOIN GOLD.DIM_DATE dd
    ON m.DATE_KEY = dd.DATE_KEY
JOIN GOLD.DIM_SECURITY s
    ON m.SECURITY_KEY = s.SECURITY_KEY
JOIN GOLD.DIM_SECTOR sec
    ON s.SECTOR_KEY = sec.SECTOR_KEY
GROUP BY
    dd.DATE_KEY,
    dd.TRADING_DATE,
    sec.SECTOR_KEY,
    sec.SECTOR;

CREATE OR REPLACE TABLE GOLD.MART_TOP_MOVERS AS
SELECT
    dd.DATE_KEY,
    dd.TRADING_DATE,
    s.SYMBOL,
    s.COMPANY_NAME,
    s.SECTOR,
    'gainer' AS MOVER_TYPE,
    m.TOP_GAINER_RANK AS MOVER_RANK,
    m.DAILY_RETURN,
    m.RANK_MOVEMENT,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM GOLD.FACT_SECURITY_DAILY_METRICS m
JOIN GOLD.DIM_DATE dd
    ON m.DATE_KEY = dd.DATE_KEY
JOIN GOLD.DIM_SECURITY s
    ON m.SECURITY_KEY = s.SECURITY_KEY
WHERE m.TOP_GAINER_RANK <= 5
UNION ALL
SELECT
    dd.DATE_KEY,
    dd.TRADING_DATE,
    s.SYMBOL,
    s.COMPANY_NAME,
    s.SECTOR,
    'loser' AS MOVER_TYPE,
    m.TOP_LOSER_RANK AS MOVER_RANK,
    m.DAILY_RETURN,
    m.RANK_MOVEMENT,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM GOLD.FACT_SECURITY_DAILY_METRICS m
JOIN GOLD.DIM_DATE dd
    ON m.DATE_KEY = dd.DATE_KEY
JOIN GOLD.DIM_SECURITY s
    ON m.SECURITY_KEY = s.SECURITY_KEY
WHERE m.TOP_LOSER_RANK <= 5;

CREATE OR REPLACE TABLE GOLD.MART_SECURITY_TREND_SIGNALS AS
SELECT
    dd.DATE_KEY,
    dd.TRADING_DATE,
    s.SECURITY_KEY,
    s.SYMBOL,
    s.COMPANY_NAME,
    s.SECTOR,
    m.MOVING_AVERAGE_SIGNAL,
    m.DAILY_RETURN,
    m.ROLLING_7_DAY_RETURN,
    m.ROLLING_30_DAY_RETURN,
    m.ROLLING_7_DAY_VOLATILITY,
    m.VOLUME_SPIKE_FLAG,
    m.RANK_MOVEMENT,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM GOLD.FACT_SECURITY_DAILY_METRICS m
JOIN GOLD.DIM_DATE dd
    ON m.DATE_KEY = dd.DATE_KEY
JOIN GOLD.DIM_SECURITY s
    ON m.SECURITY_KEY = s.SECURITY_KEY;

CREATE OR REPLACE VIEW GOLD.VW_LATEST_SECURITY_SIGNALS AS
SELECT *
FROM GOLD.MART_SECURITY_TREND_SIGNALS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SECURITY_KEY
    ORDER BY TRADING_DATE DESC
) = 1;
