CREATE SCHEMA IF NOT EXISTS UTIL;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE TABLE IF NOT EXISTS BRONZE.RAW_API_RESPONSES (
    RESPONSE_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    INGESTION_BATCH_ID STRING NOT NULL,
    SOURCE_SYSTEM STRING NOT NULL,
    ENDPOINT STRING NOT NULL,
    SYMBOL STRING NOT NULL,
    REQUEST_PARAMS VARIANT NOT NULL,
    RESPONSE_PAYLOAD VARIANT NOT NULL,
    STATUS_CODE NUMBER,
    IS_SUCCESS BOOLEAN NOT NULL,
    API_MESSAGE STRING,
    INGESTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RESPONSE_ID)
);

CREATE TABLE IF NOT EXISTS BRONZE.RAW_NASDAQ_DAILY_PRICES (
    SYMBOL STRING NOT NULL,
    TRADING_DATE DATE NOT NULL,
    OPEN_PRICE NUMBER(18, 6) NOT NULL,
    HIGH_PRICE NUMBER(18, 6) NOT NULL,
    LOW_PRICE NUMBER(18, 6) NOT NULL,
    CLOSE_PRICE NUMBER(18, 6) NOT NULL,
    VOLUME NUMBER(38, 0) NOT NULL,
    RAW_RESPONSE_ID NUMBER,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SYMBOL, TRADING_DATE)
);

CREATE TABLE IF NOT EXISTS SILVER.STG_SECURITY (
    SYMBOL STRING NOT NULL,
    COMPANY_NAME STRING NOT NULL,
    SECTOR STRING NOT NULL,
    INDUSTRY STRING NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SYMBOL)
);

CREATE TABLE IF NOT EXISTS SILVER.STG_DAILY_PRICE (
    SYMBOL STRING NOT NULL,
    TRADING_DATE DATE NOT NULL,
    OPEN_PRICE NUMBER(18, 6) NOT NULL,
    HIGH_PRICE NUMBER(18, 6) NOT NULL,
    LOW_PRICE NUMBER(18, 6) NOT NULL,
    CLOSE_PRICE NUMBER(18, 6) NOT NULL,
    VOLUME NUMBER(38, 0) NOT NULL,
    SOURCE_LAST_REFRESHED STRING,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SYMBOL, TRADING_DATE)
);

CREATE TABLE IF NOT EXISTS SILVER.STG_TRADING_CALENDAR (
    TRADING_DATE DATE NOT NULL,
    IS_WEEKDAY BOOLEAN NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TRADING_DATE)
);

CREATE TABLE IF NOT EXISTS GOLD.DIM_DATE (
    DATE_KEY NUMBER(8, 0) NOT NULL,
    TRADING_DATE DATE NOT NULL,
    DAY_OF_WEEK_NAME STRING NOT NULL,
    DAY_OF_MONTH NUMBER(2, 0) NOT NULL,
    WEEK_OF_YEAR NUMBER(2, 0) NOT NULL,
    MONTH_NUMBER NUMBER(2, 0) NOT NULL,
    MONTH_NAME STRING NOT NULL,
    QUARTER_NUMBER NUMBER(1, 0) NOT NULL,
    YEAR_NUMBER NUMBER(4, 0) NOT NULL,
    IS_WEEKDAY BOOLEAN NOT NULL,
    IS_TRADING_DAY BOOLEAN NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DATE_KEY)
);

CREATE TABLE IF NOT EXISTS GOLD.DIM_SECTOR (
    SECTOR_KEY NUMBER(38, 0) NOT NULL,
    SECTOR STRING NOT NULL,
    INDUSTRY STRING NOT NULL,
    SECTOR_INDUSTRY_NAME STRING NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SECTOR_KEY)
);

CREATE TABLE IF NOT EXISTS GOLD.DIM_SECURITY (
    SECURITY_KEY NUMBER(38, 0) NOT NULL,
    SECTOR_KEY NUMBER(38, 0) NOT NULL,
    SYMBOL STRING NOT NULL,
    COMPANY_NAME STRING NOT NULL,
    SECTOR STRING NOT NULL,
    INDUSTRY STRING NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    EFFECTIVE_START_DATE DATE NOT NULL,
    EFFECTIVE_END_DATE DATE,
    IS_CURRENT BOOLEAN NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SECURITY_KEY)
);

CREATE TABLE IF NOT EXISTS GOLD.FACT_DAILY_PRICE (
    DATE_KEY NUMBER(8, 0) NOT NULL,
    SECURITY_KEY NUMBER(38, 0) NOT NULL,
    OPEN_PRICE NUMBER(18, 6) NOT NULL,
    HIGH_PRICE NUMBER(18, 6) NOT NULL,
    LOW_PRICE NUMBER(18, 6) NOT NULL,
    CLOSE_PRICE NUMBER(18, 6) NOT NULL,
    VOLUME NUMBER(38, 0) NOT NULL,
    DOLLAR_VOLUME NUMBER(38, 6),
    INTRADAY_RANGE NUMBER(18, 6),
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DATE_KEY, SECURITY_KEY)
);

CREATE TABLE IF NOT EXISTS GOLD.FACT_SECURITY_DAILY_METRICS (
    DATE_KEY NUMBER(8, 0) NOT NULL,
    SECURITY_KEY NUMBER(38, 0) NOT NULL,
    PRIOR_CLOSE_PRICE NUMBER(18, 6),
    DAILY_RETURN NUMBER(18, 8),
    ROLLING_7_DAY_RETURN NUMBER(18, 8),
    ROLLING_30_DAY_RETURN NUMBER(18, 8),
    ROLLING_7_DAY_VOLATILITY NUMBER(18, 8),
    MA_7_CLOSE_PRICE NUMBER(18, 6),
    MA_30_CLOSE_PRICE NUMBER(18, 6),
    AVG_30_DAY_VOLUME NUMBER(38, 2),
    VOLUME_SPIKE_FLAG BOOLEAN NOT NULL,
    MOVING_AVERAGE_SIGNAL STRING NOT NULL,
    TOP_GAINER_RANK NUMBER,
    TOP_LOSER_RANK NUMBER,
    DAILY_RETURN_RANK NUMBER,
    PRIOR_DAILY_RETURN_RANK NUMBER,
    RANK_MOVEMENT NUMBER,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DATE_KEY, SECURITY_KEY)
);
